import Foundation

enum RubricLocalization {
    static let ptBR: [String: String] = [
        "English": "Inglês",
        "Math": "Matemática",
        "Mathematics": "Matemática",
        "Science": "Ciências",
        "General": "Geral",
        "Years 1-3": "Anos 1–3",
        "Years 4-6": "Anos 4–6",
        "Years 7-9": "Anos 7–9",
        "Years 10-12": "Anos 10–12",

        "Primary English Language (Years 1-3)": "Língua Inglesa do Ensino Fundamental I (Anos 1–3)",
        "Primary General Development (Years 1-3)": "Desenvolvimento Geral do Ensino Fundamental I (Anos 1–3)",
        "Primary Mathematics (Years 1-3)": "Matemática do Ensino Fundamental I (Anos 1–3)",
        "Intermediate English Language (Years 4-6)": "Língua Inglesa do Ensino Fundamental I (Anos 4–6)",
        "Intermediate General Development (Years 4-6)": "Desenvolvimento Geral do Ensino Fundamental I (Anos 4–6)",
        "Intermediate Mathematics (Years 4-6)": "Matemática do Ensino Fundamental I (Anos 4–6)",
        "Secondary English Language Arts (Years 7-9)": "Língua Inglesa – Ensino Fundamental II (Anos 7–9)",
        "Secondary General Development (Years 7-9)": "Desenvolvimento Geral – Ensino Fundamental II (Anos 7–9)",
        "Secondary Mathematics (Years 7-9)": "Matemática – Ensino Fundamental II (Anos 7–9)",
        "High School English Language Arts (Years 10-12)": "Língua Inglesa – Ensino Médio (Anos 10–12)",
        "High School Mathematics (Years 10-12)": "Matemática – Ensino Médio (Anos 10–12)",
        "High School College/Career Readiness (Years 10-12)": "Preparação para Universidade e Carreira – Ensino Médio (Anos 10–12)",

        "Listening and Comprehension": "Escuta e Compreensão",
        "Follows Class Instructions": "Segue instruções da aula",
        "Student listens and follows multi-step directions": "O aluno escuta e segue instruções de múltiplas etapas",
        "Understands Spoken Narratives": "Compreende narrativas orais",
        "Comprehends stories and explanations": "Compreende histórias e explicações",
        "Identifies Key Vocabulary": "Identifica vocabulário-chave",
        "Recognizes important words in context": "Reconhece palavras importantes no contexto",
        "Responds Appropriately": "Responde de forma apropriada",
        "Gives relevant answers to questions": "Dá respostas relevantes às perguntas",

        "Speaking and Oral Production": "Fala e Produção Oral",
        "Clarity and Pronunciation": "Clareza e Pronúncia",
        "Speaks clearly and pronounces words correctly": "Fala com clareza e pronuncia as palavras corretamente",
        "Vocabulary Use": "Uso de Vocabulário",
        "Uses appropriate and varied vocabulary": "Usa vocabulário apropriado e variado",
        "Sentence Structure": "Estrutura Frasal",
        "Forms complete and grammatically correct sentences": "Forma frases completas e gramaticalmente corretas",
        "Participation & Confidence": "Participação e Confiança",
        "Actively participates and speaks confidently": "Participa ativamente e fala com confiança",

        "Reading and Comprehension": "Leitura e Compreensão",
        "Decoding & Phonics": "Decodificação e Fonética",
        "Applies phonics skills to decode unfamiliar words": "Aplica habilidades de fonética para decodificar palavras desconhecidas",
        "Reading Fluency & Pace": "Fluência e Ritmo de Leitura",
        "Reads smoothly and at appropriate speed": "Lê fluentemente e em ritmo apropriado",
        "Understanding Text": "Compreensão do Texto",
        "Comprehends and interprets reading material": "Compreende e interpreta o material de leitura",
        "Vocabulary Acquisition from Reading": "Aquisição de Vocabulário pela Leitura",
        "Learns new words through reading": "Aprende novas palavras por meio da leitura",

        "Writing Skills": "Habilidades de Escrita",
        "Legibility & Spelling": "Legibilidade e Ortografia",
        "Writes neatly and spells words correctly": "Escreve com boa caligrafia e ortografia correta",
        "Grammar & Punctuation": "Gramática e Pontuação",
        "Uses proper grammar and punctuation": "Usa gramática e pontuação corretas",
        "Idea Organization & Expression": "Organização e Expressão de Ideias",
        "Organizes thoughts and expresses ideas clearly": "Organiza pensamentos e expressa ideias com clareza",
        "Vocabulary in Writing": "Vocabulário na Escrita",
        "Uses varied and appropriate vocabulary in writing": "Usa vocabulário variado e apropriado na escrita",

        "Social-Emotional Development": "Desenvolvimento Socioemocional",
        "Works Well with Others": "Trabalha bem com os outros",
        "Collaborates effectively and respectfully": "Colabora de forma eficaz e respeitosa",
        "Manages Emotions Appropriately": "Gerencia emoções adequadamente",
        "Handles frustration and excitement well": "Lida bem com frustração e entusiasmo",
        "Shows Respect & Kindness": "Demonstra respeito e gentileza",
        "Treats peers and adults with respect": "Trata colegas e adultos com respeito",
        "Follows Classroom Rules": "Segue as regras da sala",
        "Adheres to class expectations": "Cumpre as expectativas da turma",

        "Work Habits": "Hábitos de Trabalho",
        "Completes Tasks on Time": "Conclui tarefas no prazo",
        "Finishes work within given timeframe": "Conclui o trabalho no tempo determinado",
        "Stays Organized": "Mantém-se organizado",
        "Keeps materials and work area organized": "Mantém materiais e espaço de trabalho organizados",
        "Shows Effort & Persistence": "Demonstra esforço e persistência",
        "Tries hard and doesn't give up easily": "Esforça-se e não desiste com facilidade",
        "Asks for Help When Needed": "Pede ajuda quando necessário",
        "Seeks assistance appropriately": "Busca ajuda de forma apropriada",

        "Number Sense": "Senso Numérico",
        "Counting & Number Recognition": "Contagem e Reconhecimento de Números",
        "Identifies and counts numbers accurately": "Identifica e conta números com precisão",
        "Basic Operations": "Operações Básicas",
        "Performs addition and subtraction": "Realiza adição e subtração",
        "Number Patterns": "Padrões Numéricos",
        "Recognizes and extends patterns": "Reconhece e estende padrões",
        "Place Value Understanding": "Compreensão de Valor Posicional",
        "Understands ones, tens, hundreds": "Compreende unidades, dezenas e centenas",

        "Problem Solving": "Resolução de Problemas",
        "Word Problem Comprehension": "Compreensão de Problemas Textuais",
        "Understands what the problem is asking": "Compreende o que o problema está pedindo",
        "Strategy Selection": "Seleção de Estratégia",
        "Chooses appropriate solving methods": "Escolhe métodos de resolução apropriados",
        "Shows Work": "Mostra o processo",
        "Demonstrates thinking process": "Demonstra o processo de pensamento",
        "Checks Answers": "Confere as respostas",
        "Verifies solutions make sense": "Verifica se as soluções fazem sentido",

        "Reading and Analysis": "Leitura e Análise",
        "Comprehension of Complex Texts": "Compreensão de textos complexos",
        "Understands multi-layered narratives": "Compreende narrativas com múltiplas camadas",
        "Inference & Interpretation": "Inferência e Interpretação",
        "Reads between the lines and draws conclusions": "Lê nas entrelinhas e tira conclusões",
        "Literary Elements Recognition": "Reconhecimento de elementos literários",
        "Identifies themes, characters, plot structure": "Identifica temas, personagens e estrutura do enredo",
        "Critical Reading": "Leitura crítica",
        "Questions and evaluates what they read": "Questiona e avalia o que lê",

        "Writing and Composition": "Escrita e Composição",
        "Paragraph Structure": "Estrutura de Parágrafo",
        "Writes well-organized paragraphs with topic sentences": "Escreve parágrafos bem organizados com frases-tema",
        "Genre Writing": "Escrita de Gêneros",
        "Writes effectively in different formats (narrative, informative, persuasive)": "Escreve com eficácia em diferentes formatos (narrativo, informativo, persuasivo)",
        "Editing & Revision": "Edição e Revisão",
        "Reviews and improves own writing": "Revisa e melhora o próprio texto",
        "Voice & Style": "Voz e Estilo",
        "Develops personal writing style": "Desenvolve estilo de escrita pessoal",

        "Speaking and Presentation": "Fala e Apresentação",
        "Oral Presentation Skills": "Habilidades de Apresentação Oral",
        "Presents information clearly and confidently": "Apresenta informações com clareza e confiança",
        "Listening & Responding": "Escuta e Resposta",
        "Actively listens and responds thoughtfully": "Escuta ativamente e responde de forma reflexiva",
        "Discussion Participation": "Participação em Discussões",
        "Contributes meaningfully to class discussions": "Contribui de forma significativa nas discussões da turma",
        "Questioning Skills": "Habilidades de Questionamento",
        "Asks relevant and thoughtful questions": "Faz perguntas relevantes e reflexivas",

        "Critical Thinking": "Pensamento Crítico",
        "Analyzes Information": "Analisa informações",
        "Breaks down complex information": "Decompõe informações complexas",
        "Makes Connections": "Faz conexões",
        "Links new learning to prior knowledge": "Conecta novos aprendizados ao conhecimento prévio",
        "Asks Thoughtful Questions": "Faz perguntas reflexivas",
        "Inquires deeply about topics": "Investiga profundamente os temas",
        "Evaluates Evidence": "Avalia evidências",
        "Considers quality of information": "Considera a qualidade das informações",

        "Independence & Responsibility": "Independência e Responsabilidade",
        "Self-Directed Learning": "Aprendizagem Autônoma",
        "Takes initiative in learning": "Toma iniciativa na aprendizagem",
        "Time Management": "Gestão do Tempo",
        "Manages time and meets deadlines": "Gerencia o tempo e cumpre prazos",
        "Organization": "Organização",
        "Keeps materials and assignments organized": "Mantém materiais e tarefas organizados",
        "Goal Setting": "Definição de Metas",
        "Sets and works toward personal goals": "Define e trabalha para alcançar metas pessoais",

        "Collaboration": "Colaboração",
        "Teamwork": "Trabalho em Equipe",
        "Works effectively in groups": "Trabalha de forma eficaz em grupos",
        "Communication": "Comunicação",
        "Expresses ideas clearly to peers": "Expressa ideias com clareza aos colegas",
        "Conflict Resolution": "Resolução de Conflitos",
        "Resolves disagreements constructively": "Resolve divergências de forma construtiva",
        "Leadership": "Liderança",
        "Takes appropriate leadership roles": "Assume papéis de liderança apropriados",

        "Numerical Skills": "Habilidades Numéricas",
        "Multi-digit Operations": "Operações com Múltiplos Dígitos",
        "Performs complex calculations accurately": "Realiza cálculos complexos com precisão",
        "Fractions & Decimals": "Frações e Decimais",
        "Understands and works with rational numbers": "Compreende e trabalha com números racionais",
        "Mental Math": "Cálculo Mental",
        "Calculates efficiently without paper": "Calcula de forma eficiente sem papel",
        "Estimation": "Estimativa",
        "Makes reasonable approximations": "Faz aproximações razoáveis",

        "Mathematical Thinking": "Pensamento Matemático",
        "Problem Solving Strategies": "Estratégias de Resolução de Problemas",
        "Uses multiple approaches to solve problems": "Usa múltiplas abordagens para resolver problemas",
        "Logical Reasoning": "Raciocínio Lógico",
        "Explains mathematical thinking clearly": "Explica o raciocínio matemático com clareza",
        "Pattern Recognition": "Reconhecimento de Padrões",
        "Identifies and uses mathematical patterns": "Identifica e utiliza padrões matemáticos",
        "Real-World Application": "Aplicação no Mundo Real",
        "Applies math to practical situations": "Aplica a matemática a situações práticas",

        "Algebraic Thinking": "Pensamento Algébrico",
        "Variables & Expressions": "Variáveis e Expressões",
        "Works with algebraic expressions": "Trabalha com expressões algébricas",
        "Equation Solving": "Resolução de Equações",
        "Solves linear equations": "Resolve equações lineares",
        "Systems of Equations": "Sistemas de Equações",
        "Solves complex equation systems": "Resolve sistemas de equações complexos",

        "Geometry and Measurement": "Geometria e Medidas",
        "Geometric Reasoning": "Raciocínio Geométrico",
        "Understands translations, rotations, reflections": "Compreende translações, rotações e reflexões",
        "Measurement": "Medição",
        "Calculates area, volume, etc.": "Calcula área, volume etc.",
        "Spatial Visualization": "Visualização Espacial",
        "Visualizes and manipulates shapes": "Visualiza e manipula formas",

        "Advanced Algebra & Functions": "Álgebra Avançada e Funções",
        "Functions": "Funções",
        "Understands function concepts": "Compreende conceitos de função",
        "Complex Functions": "Funções Complexas",
        "Works with polynomial, exponential, logarithmic functions": "Trabalha com funções polinomiais, exponenciais e logarítmicas",
        "Graphing": "Gráficos",
        "Represents relationships graphically": "Representa relações graficamente",

        "Calculus & Advanced Topics": "Cálculo e Tópicos Avançados",
        "Limits & Continuity": "Limites e Continuidade",
        "Understands limit concepts": "Compreende conceitos de limite",
        "Rates of Change": "Taxas de Variação",
        "Understands changing quantities": "Compreende quantidades variáveis",
        "Integration": "Integração",
        "Understands accumulation": "Compreende acumulação",

        "Literary Analysis": "Análise Literária",
        "Analyzes themes, symbolism, and literary devices": "Analisa temas, simbolismo e recursos literários",
        "Character & Plot Analysis": "Análise de Personagens e Enredo",
        "Examines character development and narrative structure": "Examina o desenvolvimento de personagens e a estrutura narrativa",
        "Independent Interpretation": "Interpretação Independente",
        "Develops original analytical perspectives": "Desenvolve perspectivas analíticas originais",
        "Intertextual Connections": "Conexões Intertextuais",
        "Makes connections across texts and media": "Faz conexões entre textos e mídias",

        "Academic Writing": "Escrita Acadêmica",
        "Thesis Development": "Desenvolvimento de Tese",
        "Creates clear, arguable thesis statements": "Cria teses claras e argumentáveis",
        "Evidence & Citations": "Evidências e Citações",
        "Supports claims with textual evidence": "Sustenta argumentos com evidências textuais",
        "Essay Organization": "Organização de Ensaios",
        "Structures multi-paragraph essays effectively": "Estrutura redações de múltiplos parágrafos com eficácia",
        "Maintains formal, objective tone": "Mantém tom formal e objetivo",

        "Research Skills": "Habilidades de Pesquisa",
        "Source Evaluation": "Avaliação de Fontes",
        "Assesses credibility of sources": "Avalia a credibilidade das fontes",
        "Research Papers": "Trabalhos de Pesquisa",
        "Produces formal research papers": "Produz trabalhos de pesquisa formais",
        "Documentation": "Documentação",
        "Cites sources properly": "Cita fontes corretamente",
        "Synthesis": "Síntese",
        "Combines information from multiple sources": "Combina informações de múltiplas fontes",

        "Debate & Discussion": "Debate e Discussão",
        "Participates in structured debates": "Participa de debates estruturados",
        "Formal Presentations": "Apresentações Formais",
        "Delivers polished presentations": "Entrega apresentações bem preparadas",
        "Advanced Communication": "Comunicação Avançada",

        "Professional Skills": "Habilidades Profissionais",
        "Leadership & Initiative": "Liderança e Iniciativa",
        "Takes leadership in groups and activities": "Assume liderança em grupos e atividades",
        "Academic Independence": "Independência Acadêmica",
        "Self-starts learning and projects": "Inicia aprendizagem e projetos de forma autônoma",
        "Manages complex schedules and deadlines": "Gerencia agendas e prazos complexos",
        "Resilience": "Resiliência",
        "Bounces back from setbacks": "Recupera-se de contratempos",

        "College/Career Readiness": "Preparação para Universidade e Carreira",
        "Study Skills": "Habilidades de Estudo",
        "Uses effective study strategies": "Usa estratégias de estudo eficazes",
        "Note-Taking": "Anotações",
        "Takes organized, comprehensive notes": "Faz anotações organizadas e completas",
        "Test Preparation": "Preparação para Provas",
        "Prepares thoroughly for assessments": "Prepara-se de forma completa para avaliações",
        "Goal Setting & Achievement": "Definição de Metas e Conquistas",
        "Sets and achieves ambitious goals": "Define e alcança metas ambiciosas",

        "Global Awareness": "Consciência Global",
        "Current Events Knowledge": "Conhecimento de Atualidades",
        "Stays informed about world issues": "Mantém-se informado sobre assuntos do mundo",
        "Cultural Awareness": "Consciência Cultural",
        "Understands diverse perspectives": "Compreende perspectivas diversas",
        "Community Engagement": "Engajamento Comunitário",
        "Contributes to broader community": "Contribui para a comunidade em geral",
        "Social Responsibility": "Responsabilidade Social",
        "Acts as responsible global citizen": "Age como cidadão global responsável",

        "Digital Literacy": "Letramento Digital",
        "Online Research": "Pesquisa Online",
        "Conducts effective internet research": "Realiza pesquisas eficazes na internet",
        "Media Literacy": "Letramento Midiático",
        "Critically evaluates digital media": "Avalia criticamente a mídia digital",
        "Digital Citizenship": "Cidadania Digital",
        "Acts responsibly online": "Age de forma responsável online",
        "Technology Use": "Uso de Tecnologia",
        "Uses technology effectively for learning": "Usa tecnologia de forma eficaz para aprender",

        "Critical Analysis": "Análise Crítica",
        "Rhetorical Analysis": "Análise Retórica",
        "Analyzes rhetorical strategies": "Analisa estratégias retóricas",
        "Comparative Analysis": "Análise Comparativa",
        "Compares and contrasts multiple texts": "Compara e contrasta múltiplos textos",
        "Complex Textual Analysis": "Análise Textual Complexa",
        "Analyzes sophisticated literary works": "Analisa obras literárias sofisticadas",
        "Historical & Cultural Context": "Contexto Histórico e Cultural",
        "Considers texts within broader contexts": "Considera textos em contextos mais amplos",
        "Critical Theory Application": "Aplicação de Teoria Crítica",
        "Applies literary criticism frameworks": "Aplica estruturas de crítica literária",

        "Advanced Writing": "Escrita Avançada",
        "Argumentative Writing": "Escrita Argumentativa",
        "Constructs sophisticated arguments": "Constrói argumentos sofisticados",
        "Academic Integrity": "Integridade Acadêmica",
        "Maintains honesty in all work": "Mantém honestidade em todo o trabalho",
        "Academic Skills": "Habilidades Acadêmicas",
        "Handles academic pressure effectively": "Lida com pressão acadêmica de forma eficaz",
        "Professional Communication": "Comunicação Profissional",
        "Communicates in professional contexts": "Comunica-se em contextos profissionais",
        "Academic Voice": "Voz Acadêmica",
        "Demonstrates mature writing style": "Demonstra estilo de escrita maduro",

        "Problem-Solving & Creativity": "Resolução de Problemas e Criatividade",
        "Creative Thinking": "Pensamento Criativo",
        "Generates original ideas and solutions": "Gera ideias e soluções originais",
        "Innovation": "Inovação",
        "Applies creative solutions to problems": "Aplica soluções criativas a problemas",
        "Abstract Reasoning": "Raciocínio Abstrato",
        "Thinks abstractly about mathematical concepts": "Pensa de forma abstrata sobre conceitos matemáticos",
        "Mathematical Proof": "Prova Matemática",
        "Constructs rigorous mathematical arguments": "Constrói argumentos matemáticos rigorosos",
        "Geometric Proofs": "Provas Geométricas",
        "Constructs logical geometric arguments": "Constrói argumentos geométricos lógicos",
        "Mathematical Modeling": "Modelagem Matemática",
        "Creates mathematical models of real situations": "Cria modelos matemáticos de situações reais",

        "Advanced Literary Analysis": "Análise Literária Avançada",
        "Analyzes changing quantities": "Analisa quantidades variáveis",
        "College-Level Writing": "Escrita de Nível Universitário",
        "Considers ethical implications": "Considera implicações éticas",
        "Demonstrates workplace-ready skills": "Demonstra habilidades prontas para o trabalho",
        "Engages in academic discourse": "Participa do discurso acadêmico",
        "Ethical Reasoning": "Raciocínio Ético",
        "Evaluates problems from multiple angles": "Avalia problemas por múltiplas perspectivas",
        "Initiative": "Iniciativa",
        "Integrates multiple perspectives": "Integra múltiplas perspectivas",
        "Leadership Roles": "Papéis de Liderança",
        "Long-Term Planning": "Planejamento de Longo Prazo",
        "Mentoring": "Mentoria",
        "Perseveres through challenging tasks": "Persevera em tarefas desafiadoras",
        "Persistence": "Persistência",
        "Plans and executes extended projects": "Planeja e executa projetos de longo prazo",
        "Records information effectively": "Registra informações de forma eficaz",
        "Reflects on strengths and areas for growth": "Reflete sobre pontos fortes e áreas de melhoria",
        "Self-Management": "Autogestão",
        "Self-Reflection": "Autorreflexão",
        "Stress Management": "Gestão do Estresse",
        "Style & Sophistication": "Estilo e Sofisticação",
        "Supports and guides peers": "Apoia e orienta colegas",
        "Textual Analysis": "Análise Textual",
        "Transformations": "Transformações",
        "Works independently at college level": "Trabalha de forma independente em nível universitário"
    ]
    
    static func localized(_ key: String, languageCode: String) -> String {
        guard languageCode == "pt-BR" else { return key }
        return ptBR[key] ?? key
    }
}
